[EngineSettings.General]
ApplicationType = 0
EngineAuthor = 'Neuvex IT & Consultancy'
EngineName = 'StrandEngine'
EngineVersion = '1.0.0'

[EngineSettings.Graphics]
DepthFormat = 30
GraphicsAPI = 1
ImageCount = 2
PresentMode = 2
SwapchainFormat = 16
ThreadCount = 4